project:
  type: website
  output-dir: _site
website:
  title: "Teaching Connectomics"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Education Modules
      - code-tutorials.qmd
    tools: 
      - icon: github
        menu:
          - text: Tutorial Code
            url:  https://github.com/AllenInstitute/Teaching_Connectomics
  back-to-top-navigation: true
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link-external-newwindow: true
  pdf:
    pdf-engine: 'lualatex' 