project:
  type: website
  output-dir: _site
website:
  title: "Teaching Connectomics"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Education Modules
      - code-tutorials.qmd
    tools: 
      - icon: github
        menu:
          - text: Tutorial Code
            url:  https://github.com/AllenInstitute/Teaching_Connectomics
  back-to-top-navigation: true
  
filters:
  - _filters/task.lua
  - quarto
  - _filters/gridtables.lua

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    link-external-newwindow: true
  pdf:
    pdf-engine: lualatex
    documentclass: report
    geometry: margin=1in
    fontsize: 11pt
    toc: false
    number-sections: false
    mainfont: "SourceSans3-Regular.otf"
    mainfontoptions:
      - "Path=fonts/"
      - "ItalicFont=SourceSans3-It.otf"
      - "BoldFont=SourceSans3-Bold.otf"
      - "BoldItalicFont=SourceSans3-BoldIt.otf"
    include-in-header: "tex/preamble.tex"
    template-partials:
      - "tex/before-body.tex"