project:
  type: website
  output-dir: _site
website:
  title: "Teaching Connectomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: module-1.qmd
        text: Module 1
    tools: 
      - icon: github
        menu:
          - text: Tutorial Code
            url:  https://github.com/AllenInstitute/Teaching_Connectomics
  back-to-top-navigation: true
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
  pdf:
    pdf-engine: 'lualatex'
    